languageCode = "fr-fr"
theme = "ba"
summaryLength = "10"
paginate = 50
title = "B.A. 79"
baseurl = "/"

[params]
mobile = ""
mentionsURL = "/mentions-legales"
author_image = ""
copyright = "Tous droits réservés &copy; 2020"
bio = "..."
search = true
layout = "1"
author = "Béatrice"
logo = "images/logo-banner-512.png"
contactUrl = "/nous-contacter"
contact_form_action = "#"
address = "..."
mainModal=true
urlSoutenir="/soutenir"
facebookPage = "https://www.facebook.com/Ici-drive-107385147684083/"
preloader = true
google_analitycs_id = "UA-181036051-1"
email = "b.a.79@laposte.net"
description = "Si vous cherchez à sauver des chatons et des chats de l’euthanasie et/ou de l’abandon, vous êtes sur le bon site. Vous pourrez trouver des chatons et des chats recueillis par l’Association B.A. 79 sur la page d’accueil du site. Pour chacun des animaux, vous disposerez des informations concernant son âge, son sexe, son caractère, les soins qui lui ont été apportés, ainsi que le montant de la participation demandée lors de l’adoption. Chaque annonce est accompagnée d’une photographie. Vous pourrez également découvrir l’association dans la rubrique qui lui est consacrée : statuts, nouvelles des adoptés, comptes rendus d’assemblées, actualité. La rubrique « Soutenir » détaille la manière de contribuer au développement de l’association, par les dons, les projets et les opérations spéciales. Pour devenir famille d’accueil, une rubrique permet de connaître toutes les modalités : le contrat type, les soins à apporter, le rôle de chacun. Enfin, la rubrique « Comment adopter ? » présente toutes les étapes de l’adoption : depuis la rencontre avec l’animal jusqu’au changement de propriétaire. Le site présente également des liens vers les partenaires de l’association, ainsi que son site Facebook."
home = "Accueil"

[params.plugins]

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

[[params.plugins.js]]
link = "plugins/headroom/headroom.js"

[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"

[[params.plugins.js]]
link = "plugins/masonry/masonry.js"

[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"

[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"

[[params.plugins.js]]
link = "plugins/search/fuse.min.js"

[[params.plugins.js]]
link = "plugins/search/mark.js"

[[params.plugins.js]]
link = "plugins/search/search.js"


[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"

[outputs]
home = ["HTML", "RSS", "JSON"]


[menu]

[[menu.main]]
name = "Comment adopter ?"
URL = "comment-adopter"
weight = 2

[[menu.main]]
name = "Devenir famille d'accueil"
URL = "devenir-famille-accueil"
weight = 3

[[menu.main]]
name = "L'association"
URL = "association"
weight = 4

[[menu.main]]
name = "Soutenir"
URL = "soutenir"
weight = 5

[[menu.main]]
name = "Nous contacter"
URL = "nous-contacter"
weight = 6