backend:
  name: git-gateway

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "chatons" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Chaton" # Used in the UI, ie.: "New Post"
    folder: "site/content/chatons" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Nom", name: "nom", widget: "string" }
      - label: "Sexe"
        name: "sexe"
        widget: "select"
        options:
          - {label: "Mâle", value: "M" }
          - {label: "Femelle", value: "F" }
      - {label: "Date de naissance", name: "datedenaissance", widget: "date", format: "DD/MM/YYYY" }
      - label: "Etat"
        name: "etat"
        widget: "select"
        options:
          - {label: "Disponible", value: "disponible" }
          - {label: "Réservé", value: "reserve" }
          - {label: "Adopté", value: "adopte" }
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image alt (SEO)", name: "imageAlt", widget: "string"}
      - {label: "Participation", name: "montantremoursement", widget: "number" }
      - {label: "Tags", name: "tags", widget: "list" }
      - {label: "Caractère", name: "traits", widget: "list" }
      - {label: "Soins réalisés", name: "soinsfaits", widget: "list" }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "config.toml"
        label: "Configuration"
        name: "conf"
        extension: "toml"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "site/content/association.md"
        label: "L'association"
        name: "association"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Date de publication", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image alt (SEO)", name: "imageAlt", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list" }
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/comment-adopter.md"
        label: "Comment adopter ?"
        name: "comment-adopter"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Date de publication", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image alt (SEO)", name: "imageAlt", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list" }
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/devenir-famille-accueil.md"
        label: "Devenir famille d'accueil"
        name: "devenir-famille-accueil"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Date de publication", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image alt (SEO)", name: "imageAlt", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list" }
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/soutenir.md"
        label: "Soutenir"
        name: "soutenir"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Date de publication", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image alt (SEO)", name: "imageAlt", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list" }
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/nous-contacter.md"
        label: "Nous contacter"
        name: "nous-contacter"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Date de publication", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image alt (SEO)", name: "imageAlt", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list" }
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "site/content/mentions-legales.md"
        label: "Mentions légales"
        name: "mentions-legales"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Date de publication", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image alt (SEO)", name: "imageAlt", widget: "string"}
          - {label: "Tags", name: "tags", widget: "list" }
          - {label: "Body", name: "body", widget: "markdown"}
